### ISSUE TITLE
Cannot connect to socket

### ISSUE THREAD

**Issue by TriPSs** [btford/angular-socket-io#110]
I'm trying to connect to my socket with the following code:

>    module.factory('Socket', ['socketFactory', function(socketFactory){
>      var mySocket;
>
>      return function(){
>        var myIoSocket = io.connect('http://api.example.nl:3000');
>
>           mySocket = socketFactory({
>              ioSocket: myIoSocket
>           });
>
>          return mySocket;
>       };
>
> }]);

When i use the socket.io js library i can connect with:

>var socket = io('http://api.example.nl:3000');

Why isn't it working with the angular version?

**Comment by analytik** [comment]
Not sure if this helps, but when I had a similar problem, I figured out I need to specify path separately, e.g.
```   var myIoSocket = io.connect('http://api.example.nl:3000', {path: 'foo/bar/});```

**Comment by TriPSs** [comment]
Little late but i changed it to:

``` javascript
var socket = io.connect('http://api.example.nl:3000');
socket.connect();
```
