### ISSUE TITLE
Connected but receiving polling error on Chrome Browser

### ISSUE THREAD

**Issue by kiexcolo** [btford/angular-socket-io#114]
I am using angular-socket-io to connect angular frontend to express server. My express console logs "connected" but on browser I keep getting *"GET http://qapp.com/socket.io?EIO=3&transport=polling&t=1433303600969-87 404 (Not Found)"* and I also cannot receive any messages from the server. Socket-io 1.3.5 is referenced in my index.php. I am quite new to angular js and socket io so I am not sure if I may have made a mistake somewhere, any help will be appreciated. 

(Note that I have googled this issue but the remedies usually apply to the setting up of the server side code which I think I have done correctly...)

This is my server side code:
```JavaScript
var express = require('express');
var app = express();
var server = require('http').createServer(app);
var io = require('socket.io')(server);
var redis = require('redis');

server.listen(8090);
io.on('connection', function(socket){
  console.log("connected");
  var redisClient = redis.createClient();
  redisClient.subscribe('message');
 
  redisClient.on("message", function(channel, message) {
    console.log("new message in queue " + message + "channel:" + channel);
    socket.emit("message", message);
  });
 
  socket.on('disconnect', function() {
    redisClient.quit();
  });
});
```

App.js
```JavaScript
var app = angular.module('myapp',['ngRoute','ui.bootstrap','btford.socket-io']);

app.
factory('socket', function (socketFactory) {
  
  var myIoSocket = io('http://localhost:8090');
  var socket = socketFactory(myIoSocket);
  socket.forward('message');
    
  return socket;
});

...
```

Controller.js
```JavaScript
app.controller('adminController', function($scope, $http, socket) {
            
    socket.on('message', function(data) { 
        console.log(data);    
	}); 
...
```

Update (Tried with normal Socket IO, was able to connect and receive messages without polling errors, so the server portion should be ok)
```
    <script>
        var socket = io.connect('http://localhost:8090');
        socket.on('message', function(msg) {
                  console.log(msg);
                  });
    </script>
```

**Comment by kiexcolo** [comment]
Never mind I will just use regular Socket IO.

**Comment by jainshravan123** [comment]
Hi Kiexcolo,

How did you resolve this error and i am not getting the right answer from anywhere. Please help me.
