### ISSUE TITLE
request isn't sent on iOS 10.0

### ISSUE THREAD

**Issue by wiadev** [btford/angular-socket-io#150]
Hi @btford 

I've been using this problem till iOS 9.3.5 but after upgrade to iOS 10.0, it stops sending emit request to socket server.

I've checked the request logs on heroku and from iOS 9.3.5, Andorid and Web Browser, we are getting the request correctly but from iOS 10, no requests.

Any suggestions? 

Thanks.

**Comment by raymondSmith501** [comment]
I had the same problem and couldn't connect.  For me it was adding the web socket protocol into the Content Security Protocol.  Here is where I found the answer
https://github.com/thelounge/lounge/issues/580

**Comment by wiadev** [comment]
@stich12 Thanks for the previous answer. it works great.

I have another question.
can we somehow delay the disconnection?
for example, while A and B was having a chat and A's iphone screen was locked by mistake.
but at this point, the socket server receives the disconnection request instantly and it makes the A drops the chatting room and chat was disconnected.

so can we delay receiving the disconnection request somehow like 1 min? so user can easily reconnect to the chat session without re-create.

Thanks.
