### ISSUE TITLE
adding support for AMD/Webpack

### ISSUE THREAD

**Issue by mavrick** [btford/angular-socket-io#155]
Hey there, 

I'm currently rebuilding my site to use webpack because I'm wrapping it up for use within Electron however I run across this error when including ``angular-socket-io`` library:

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module website due to:
Error: [$injector:modulerr] Failed to instantiate module {} due to:
Error: [ng:areq] Argument 'module' is not a function, got Object
http://errors.angularjs.org/1.6.3/ng/areq?p0=module&p1=not%20a%20function%2C%20got%20Object
```
code:
```javascript
import socketIo from 'angular-socket-io';

var app = angular.module("website", [socketIo]);
```

I'm using ES6 with Babel and Webpack. Any help would be appreciated.

**Comment by mavrick** [comment]
So, to answer my own question. It can be done like this:

```javascript
import 'angular-socket-io';

var app = angular.module("website", ["btford.socket-io"]);
```

**Comment by afeish** [comment]
+1. I come with this question too. I have to set the literal of the module manually, which is not consistent with my ES6 import style.

**Comment by casterfile** [comment]
mport 'angular-socket-io';

var app = angular.module("website", ["btford.socket-io"]);

I am having the same problem.... if i try  to add ", ["btford.socket-io"]"  nothing is loaded....
