### ISSUE TITLE
How to emit to a namespace

### ISSUE THREAD

**Issue by Cadrach** [btford/angular-socket-io#51]
Hi, 
I am new to Socket.io and want to integrate it to my angular project using your lib. I cannot find a way to emit to a specific namespace. In native Socket.io I guess I would do something like this:

```
socket.of('/namespace').emit(eventName, data, callback)
```

But there is no access to the "of" method or anything like that. Am I missing something or is this something I should add on my own?

**Comment by ghost** [comment]
this seems not working on me. The client gets "Cannot GET"
