### ISSUE TITLE
Connecting after authentication

### ISSUE THREAD

**Issue by jrthib** [btford/angular-socket-io#64]
I have an angular app with a login form. Once authenticated my auth service will forward to the inner protected state of the Angular app. Within this, I would like to have the web socket open it's connection. Currently to achieve this I have to refresh the page after authenticating, then the socket connection occurs. 

Do you have any recommendations on how to achieve this?

**Comment by Razgort** [comment]
Like it is said here : https://github.com/rakeshok/socket.io-client-cookie
If you want to check for authentification you need to get the cookie. Or socket.io-client does not allow to send cookies apparently ....
If someone find a fix or a wait to use the patch in angular, I'll take it =)

**Comment by frey1esm** [comment]
Using the above code, when a user is logged out and logged back in without app refresh, there is a new connection to the server but angular does not see it and thinks there is no connection. Anyway to refresh angular to successfully reconnect to the server?
