### ISSUE TITLE
"io is not defined" error when using MEAN.js

### ISSUE THREAD

**Issue by skyserpent** [btford/angular-socket-io#77]
Hey everyone, I'm using socket.io@0.9.x and I have made a gist of my angular controller here:
https://gist.github.com/skyserpent/832f980ca9ed9ed30e4b

My JS assets are loaded like this:
    ...
    '//cdnjs.cloudflare.com/ajax/libs/socket.io/0.9.16/socket.io.min.js',
    'public/lib/angular-socket-io/socket.js'

I have even included 'btford.socket-io' in Angular's 'applicationModuleVendorDependencies' but for some reason I get an error saying "io is not defined" in line 6 of the gist I uploaded.

Any help is much appreciated.

**Comment by adaptivedev** [comment]
This didn't fix my problem with this same error. What's this bad gateway possibly about?

http://chat.socket.io/socket.io/socket.io.js Failed to load resource: the server responded with a status of 502 (Bad Gateway)
ionic.bundle.js:21157 ReferenceError: io is not defined
    at Object.<anonymous> (services.js:13)
