### ISSUE TITLE
io.connect() on injection

### ISSUE THREAD

**Issue by deltaepsilon** [btford/angular-socket-io#8]
The moment I inject the socket service, the service calls io.connect() and fires off a call to my server at /socket.io/1?t=123456.

I need to connect my socket to a very specific route. I cannot see any other calls to to io.connect() in your code, so I'm a bit lost.

Have you provided a way to connect to an arbitrary path?

**Comment by opyate** [comment]
As of Socket.io version 1, resource has been replaced by path. Use:

    var socket = io('http://example.org', {path: '/your/path'});
    return  socketFactory({
        ioSocket: socket
    });
