### ISSUE TITLE
transport=polling not found

### ISSUE THREAD

**Issue by connor11528** [btford/angular-socket-io#82]
I am trying to set up an express 4 server using socket.io and an angular frontend. I keep getting errors in the console and the browser about `transport=polling` not found.

In the terminal: `GET /socket.io/?EIO=3&transport=polling&t=1411419424649-79 404 0.486 ms - 74`

In the browser: `Failed to load resource: the server responded with a status of 404 (Not Found)  http://localhost:3000/socket.io/?EIO=3&transport=polling&t=1411419457464-84`

What creates these errors?

**Comment by ateixeiramunoz** [comment]
Nice, it also solved my Issue With Express, angularjs,  Centos server,  and virtualized apps.
