### ISSUE TITLE
Issue specifying external socketio server

### ISSUE THREAD

**Issue by liamfd** [btford/angular-socket-io#87]
I realize this might be a dumb question, but I've been through the other posts on here and the docs a few times, and I haven't been able to figure out how to do it. How do I specify the location of the socket I want to connect to? I'm using an external service for the server side of my app, which is just an Express server with socketio.

I've tried setting it up in the config, so doing this:

``` javascript
config([function (socketFactory) {
  socketFactory.ioSocket(io.connect('http://website.com/some/path:443'));
})
```

But that's throwing an error, as socketFactory appears to be undefined. I'm using socketFactory instead of socketProvider because of https://github.com/btford/angular-socket-io/issues/74, the example from the docs is also not working.

I suppose the first question should be, am I correct in thinking that this is where the server should be specified, or should it be done somewhere else? If this is the correct place to do it, what am I doing wrong?

Basically, I just want to be able to do this:

``` javascript
var socket = io('http://website.com/some/path:443');
```

The way I would in a standard socketio client.

The full code: 

``` javascript
// Declare app level module which depends on filters, and services
angular.module('myApp', ['myApp.filters', 'myApp.services', 'myApp.directives', 'btford.socket-io']).
  config(['$routeProvider', '$locationProvider',
    function($routeProvider, $locationProvider, socketFactory) {
      $routeProvider.
        when('/', {
          templateUrl: 'partials/index',
          controller: IndexCtrl
        }).
        when('/addPost', {
          templateUrl: 'partials/addPost',
          controller: AddPostCtrl
        }).
        when('/readPost/:id', {
          templateUrl: 'partials/readPost',
          controller: ReadPostCtrl
        }).
        when('/editPost/:id', {
          templateUrl: 'partials/editPost',
          controller: EditPostCtrl
        }).
        when('/deletePost/:id', {
          templateUrl: 'partials/deletePost',
          controller: DeletePostCtrl
        }).
        otherwise({
          redirectTo: '/'
        });
      $locationProvider.html5Mode(true);
      socketFactory.ioSocket(io.connect('http://website.com/some/path:443'));
    }
  ]).
  factory('socket', function (socketFactory) {
    var socket = socketFactory();
    return socket;
  }
);
```

I'm new to Angular (all of the routing stuff is coming from https://github.com/btford/angular-express-seed) so I imagine it's just something I'm not getting about the framework, but any help would be appreciated. Also, if it's not just an obvious error on my part, would it be possible to add a section on this to the docs, and/or correct the existing examples?

Edit: 
I see that I did, in fact, miss something important in the docs. It appears that this is a way to do it:

``` javascript
  factory('socket', function (socketFactory) {
    var io_socket = io('https://my-notifications.com:443');
    var socket = socketFactory(io_socket);
    socket.forward('message');
    return socket;
  }
```

Now I just have to try to get forward working.

**Comment by opyate** [comment]
@liamfd 
> var socket = io('http://website.com/some/path:443');

For future reference, the port comes after the host:

    var socket = io('http://website.com:443/some/path');
