### ISSUE TITLE
.forward only passes first parameter of event's data

### ISSUE THREAD

**Issue by naholyr** [btford/angular-socket-io#89]
``` js
// server side
socket.emit("event", "data1", "data2")

// client side
socket.forward("event", $scope);
$scope.$on("socket:event", function (scope, data1, data2) {
  console.log(data1); // "data1"
  console.log(data2); // undefined
});
```

I'd expect `data2` to be defined in previous code sample. Is it a shared opinion?

**Comment by davisford** [comment]
@naholyr, I sent a PR that fixes this, but he killed it b/c it did not have a test.  YMMV, but it works and fixes the problem if you want to take the fix a la carte.
