### ISSUE TITLE
Addition of rooms

### ISSUE THREAD

**Issue by elliott-davis** [btford/angular-socket-io#9]
Would it be possible to add a rooms function?  I was specifically looking at https://github.com/LearnBoost/socket.io/wiki/Rooms.

**Comment by NavneetNile** [comment]
Hi @elliott-davis and @btford , I have a similar requirement. Could you explain how you solved it? I want to be able to publish messages to a room, and to push them to all the other users who are a part of that room, without sending it out to every user seprately. How did you do the pub/sub solution ?

**Comment by Beny-Muler** [comment]
Did someone solved that on client side?
